name: salla
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  conditional_builder_null_safety: ^0.0.4
  bloc: ^7.1.0
  flutter_bloc: ^7.2.0
  dio: ^4.0.0
  shared_preferences: ^2.0.7
  smooth_page_indicator: ^1.0.0
  fluttertoast: ^8.2.4
  carousel_slider: ^4.0.0
  image_picker: 0.8.1+4
  cached_network_image: ^3.3.0
  readmore: ^2.2.0
  meta: ^1.9.1
  flutter_screenutil: ^5.9.0
  go_router: ^13.0.0
  equatable: ^2.0.5
  envied: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  envied_generator: ^0.5.2
  build_runner: ^2.4.7

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Jannah
      fonts:
        - asset: assets/fonts/jannah.ttf
          weight: 700
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
